### ISSUE TITLE
Improve task switching visualization

### ISSUE THREAD

**Issue by BryonLewis** [arclamp/annotation-tracker#14]
There is some confusion with the current state (running/stopped) for a task when switching between different tasks.  Attempt to make this clearer by defining what occurs when switching tasks and a better way to visualize it.

Some clarifications needed:
- Need to check if there is a difference between pausing and stopping 
- Is starting/stopping a task different then pausing/resuming a task and does it need to be that way.

Options for what happens when switching tasks:
- Pause current task and notify user that the task is paused and they need to explicitly start a new one
- Stop current task
- Stop current task and notify user that the current task has been stopped and that they need to enable a new task
- Stop current task and automatically start next task
- Stop current task and automatically start selected task with user notification that a new task has started.

Visualization Options for task status:
- Color indications along with icons.
- In the task list some more visual indications into the select tasks state besides the radio button, stuff like icons indicating what is occuring.
- During switching of tasks some brief (1-3 second) animation applied to the current task in the list to indicating the change in state.
- Toast notifications (can be annoying given frequency of changing tasks)

**Comment by BryonLewis** [comment]
Only have two states, paused and running.

**Comment by waxlamp** [comment]
> There is some confusion with the current state (running/stopped) for a task when switching between different tasks. Attempt to make this clearer by defining what occurs when switching tasks and a better way to visualize it.
> 
> Some clarifications needed:
> 
> * Need to check if there is a difference between pausing and stopping

In general, there is not. The only exception is that advancing past the last task should enter the "paused" state and deselect all tasks. This is the only time we might be said to be entering a "stopped" state, but we are explicitly removing the stop button which explicitly enters this state.

> * Is starting/stopping a task different then pausing/resuming a task and does it need to be that way.

I don't believe there are any such distinctions.

> 
> Options for what happens when switching tasks:
> 
> * Pause current task and notify user that the task is paused and they need to explicitly start a new one
> * Stop current task
> * Stop current task and notify user that the current task has been stopped and that they need to enable a new task
> * **Stop current task and automatically start next task**
> * Stop current task and automatically start selected task with user notification that a new task has started.

The bolded one above. The principle here is to *minimize* the user's awareness of the task-tracking UI.

> 
> Visualization Options for task status:
> 
> * Color indications along with icons.
> * In the task list some more visual indications into the select tasks state besides the radio button, stuff like icons indicating what is occuring.

We are looking at three redundant encodings of the current state:
1. The button for toggling state shows the icon for the state that will be entered (play icon when in the paused state; pause icon when in the running state).
2. If a task is selected, its background shows the current state via color--green for running, red for paused (or whatever colors you choose; green/red is famously troublesome for colorblind users, but the green/red traffic light metaphor carries a lot of weight).
3. There's a text indicator explicitly saying what state the system is in.

> * During switching of tasks some brief (1-3 second) animation applied to the current task in the list to indicating the change in state.

This is a good idea, but it needs to be subtle (3 seconds is much too long; even 1 second is pushing it). After you prototype something, please share with us so we can "alpha test" it.

> * Toast notifications (can be annoying given frequency of changing tasks)

Let's not do this one--I agree about frequency+annoyance, and it violates our constraint of minimizing user awareness of the task switching UI.

**Comment by BryonLewis** [comment]
This is a really quick rough pass once I set up the dev environment:
![image](https://user-images.githubusercontent.com/61746913/129108568-d3e6f45d-441a-4274-8da5-cb5aa96bd16b.png)
When closed in the Task name it will display the color status if the section is collapsed
![image](https://user-images.githubusercontent.com/61746913/129108600-bbf87b00-7b92-486f-b37f-d639ea8e7d76.png)
![image](https://user-images.githubusercontent.com/61746913/129108793-92f76d52-524c-4670-9f1f-f2c7cea555b5.png)
![image](https://user-images.githubusercontent.com/61746913/129108832-2ca88930-2b84-4a8f-abcf-3c98337a2b7a.png)

I still think the play button may need something more to draw attention.

**Comment by waxlamp** [comment]
This looks great.

What's the reason you think the play button needs a focus of attention on it?

You could try adding a flashing "record" light (a solid red circle) to the corner of the play/pause button when it's in the running state. Or if you're not talking about redundant encoding of the state, maybe just shade the button a light gray?

**Comment by BryonLewis** [comment]
> What's the reason you think the play button needs a focus of attention on it?

I don't know what kind of instructions are provided so I didn't know if it was clear that when you start you need to click play to begin.  It starts with Task 1 selected and in the paused state.  That may be enough to tell a user they need to click play to begin.

**Comment by waxlamp** [comment]
I assume they'll have a training period when they run their studies. But maybe this is a good question for the customer.

**Comment by BryonLewis** [comment]
should I we schedule a quick demo to make sure I didn't miss anything?

**Comment by waxlamp** [comment]
> should I we schedule a quick demo to make sure I didn't miss anything?

For the paper trail: Bryon and I discussed yesterday and resolved his remaining questions:
- gray out the "forward" button when the state is paused
- ask the customer if more highlighting/attention is needed on the play button (but Roni doesn't think this is needed)

**Comment by BryonLewis** [comment]
They start with no task selected and the play/pause buttons disabled.  There was talk of having a red indicator for a stopped task, but I think it makes sense to have a red indicator indicate no selected task.
Start session is the first button they click before doing anything.  This in turn starts the session and selects the first task in the pause state.  The start  session button turns into a stop session button which is used to stop the session.

They then need to click on the play/pause button to start the first task.  They can choose any other task in the list before clicking play as well.

Keyboard Shortcuts:
- 1-9 - Associated with task numbers in order
- space-bar - pause/play task
- escape  - stop (end current session and when they start (play) it's a new session)
- enter - move to the next task in order, same as next button

**Comment by waxlamp** [comment]
>The start session button turns into a stop session button which is used to stop the session.

This should be an "end session" button to indicate the stronger action triggered by the button. It's not a resumable stopped state; you're ending/closing a session.

**Comment by BryonLewis** [comment]
Just some notes to myself about the current update

![Selection_283](https://user-images.githubusercontent.com/61746913/130367434-fca47969-567d-46ef-9f2d-a5650e54917f.png)

Updated the activityLogger.js to not record information be default.  There are now two more functions (`startSession` and `stopSession`).  These functions act to start the recording and create a new UID for the session.
There are some guards around recording where the activity logger needs to have a new flag `this._sessionStarted` true to be recording data.

- Added the new button with the start/end session text and red/green background.
- Play/Next buttons are disabled at the start
- Added in the fact that if the user tries to select a task by clicking on it it will flash the start session button.
- The user clicks start session and play/pause are enabled and the task list is expanded so the user can select a task.  The current task is in the pause state and the user needs to hit play to start it.
- After all that it behaves like before in relation to task and advancement
- The End Session button unselects all tasks and 
- Added in the keyboard shortcuts specified but they are bound to the document, need to check for problems.

Questions to task (most likely for David Manthey):
- Confirm my modification of the `sessionId` creation works well with the `activityLogger`
- Keyboard shortcuts and if they should be done in a different way, other than binding them to document when the metadata is loaded.

Testing left to do:
Need to test the logging for the start/stop session and make sure it's actually recording new sessionIds.

**Comment by BryonLewis** [comment]
Note to self:
- `preventDefault`/`stopPropogation` or whatever it is to handle conflicting key-controls in geoJS.  Specifically the 0-9 keys having `mapInteractor` effects
- Store the image from imageOpened so that when the user starts a session it is recorded
- Test that swapping images work
- Confirm logged results.

**Comment by manthey** [comment]
Added in #19.
