### ISSUE TITLE
 setuptools-scm was unable to detect version for '/mnt/md0/wsi/annotation-tracker'

### ISSUE THREAD

**Issue by sunaifei** [arclamp/annotation-tracker#28]
When i install the package, error " setuptools-scm was unable to detect version for '/mnt/md0/wsi/annotation-tracker'" happened.

**Comment by manthey** [comment]
Do you still have an issue after #33 was merged?  Reopen if you do.

**Comment by sunaifei** [comment]
> Do you still have an issue after #33 was merged? Reopen if you do.

 readme is an rst file in my folder
