### ISSUE TITLE
Display all tasks in experiment panel

### ISSUE THREAD

**Issue by waxlamp** [arclamp/annotation-tracker#4]
Use color or other indicator to show which one is active. One recent idea is to use a "traffic light" metaphor: a green "light" that behaves much like a radio button, highlighting the active task. Keep in mind that many people are colorblind, so the usual red/green pairing may not be ideal.

This issue likely depends on #7.

From Pete Lawson:
> Seeing it implemented I think it might be nice to see all of the experiment tasks in a vertical list, rather than seeing just the current one running. This way there is some context about how many tasks are in the experiment, and there could be a visual indicator to show the active task, and maybe a color change to indicate running (green) and paused (red), or something to that effect.

**Comment by BryonLewis** [comment]
I'm assuming this is the next task that you wanted me to implement.  I want to add this quoted comment to it from the previous PR:

>The only thing I'd suggest adding is a change in the display of experiment/task: the panel should show the experiment at the top, then all tasks in a list, with the currently active task in bold (or some other visual standout indicator). We'll need to refine this design as we go, but "show the active task in context of all tasks" is a design feature we already know we need.

**Comment by waxlamp** [comment]
Yes, please implement this next. Thanks for finding this issue; I'd forgotten that I opened it!

**Comment by BryonLewis** [comment]
More exploratory to see what would work the best right now.  Looking for any and all feedback or let me know if you want to have a discussion on it.  I need to do a bit more thinking about how this would work.

https://user-images.githubusercontent.com/61746913/110720409-7f180180-81dc-11eb-887c-c7646e280179.mp4

**Comment by waxlamp** [comment]
Bryon, this prototype looks fantastic. In fact, I think this may be enough to call a meeting with Tulane to show them this and collect their feedback (and perhaps even press them to give us a realistic task list with descriptions so we can use that instead of our faked up example here).

A few notes off the top of my head:
1. I might have missed it but what happens when you click on the pause button? I would assume that the header would change to having `(paused)` after the task title, but the task would remain selected.
2. There should be a "next" button that advances the task selector to the next task, and maybe goes into the stop state if you are already on the last task. This would be in addition to being able to select the task you're on.
3. I don't think the stop button should behave the way it does. I am uneasy at the idea of losing the previous state (i.e., which task was selected) when it is clicked. I'll need to review our work description to remember how such a button should work (if it's even called for).
4. The user input stuff is interesting, and could be useful to the intended use case, but we'll need to show it to Tulane and see if it sparks their imagination.
5. In general, I believe we'll want to streamline this bit of UI (whatever "streamline" means). For me, it's a matter of keeping it simple enough that a user can't get lost in the state transitions available to them. Keep in mind, this panel is a necessary evil to running these user studies--if we could get away with not having it, and instead using some crazy analysis routine after the fact to reconstruct what they were doing (which task, etc.) at each moment, we'd use that. That being the case, this UI needs to be as simple as possible.

**Comment by BryonLewis** [comment]
1.  Yeah when you click the pause button it will change the header (paused) and the icon for the play button.  I'm not currently happy with the current difference between the play/pause icons and may look into something a bit more representative (possibly a record button with depressed state and color for being active).
2. I can add that next button back in. 
3. I was basing this on David's comment:  "We do want a "stop" condition where no experiment is selected or running.
" (https://github.com/arclamp/annotation-tracker/pull/10#issuecomment-790819395).  This can easily be removed or modified.
4. I know there was talk of it, so I just added in some simple JSON parsing stuff just to visualize quickly.  I think any user input needs to have a help or description associated with it so a user knows exactly what is expected.  Plus it might require some sort of validation.
5. This is where I was struggling the most.  I think without having examples that encompass the breadth of the type of tasks and running through them several times myself I am generalizing a lot of possible user experiences.  So I could be making some inaccurate assumptions.
Examples:
-   I don't know if a task takes 30 seconds or 3 minutes (30 seconds and I wouldn't have a collapsible long list, I would have a scrolling list with it centered on current task for faster switching)
- Right now behavior on switching tasks is to pause the current one and select a new one with it paused, should it immediately start?
-   I don't know if the task title is enough information or if there needs to be a lengthy persistent description to refer to.

**Comment by waxlamp** [comment]
> 1. Yeah when you click the pause button it will change the header (paused) and the icon for the play button.  I'm not currently happy with the current difference between the play/pause icons and may look into something a bit more representative (possibly a record button with depressed state and color for being active).

This is good to think about but I would file an issue so we can revisit it later. Currently, play/pause icons are what has been requested, so we should start there and offer improvements after we have something basic working (which we do, with the current play/pause button).

> 2. I can add that next button back in.

👍🏾 

> 3. I was basing this on David's comment:  "We do want a "stop" condition where no experiment is selected or running.
>    " ([#10 (comment)](https://github.com/arclamp/annotation-tracker/pull/10#issuecomment-790819395)).  This can easily be removed or modified.

This is true, but I am not sure whether there should be a *button* that enters this state. But leave it there for now and we'll show it to Tulane to see what they think about it.

> 4. I know there was talk of it, so I just added in some simple JSON parsing stuff just to visualize quickly.  I think any user input needs to have a help or description associated with it so a user knows exactly what is expected.  Plus it might require some sort of validation.

Sounds good. Again, don't spend any more effort on this right now, because we don't have enough requirements from the customer to know how better to shape this at the moment.

> 5. This is where I was struggling the most.  I think without having examples that encompass the breadth of the type of tasks and running through them several times myself I am generalizing a lot of possible user experiences.  So I could be making some inaccurate assumptions.
> 

Agreed. My comment was much more general, and you're right that this will require a lot of feedback from Tulane to get right.

> **Examples:**
> 
> * I don't know if a task takes 30 seconds or 3 minutes (30 seconds and I wouldn't have a collapsible long list, I would have a scrolling list with it centered on current task for faster switching)

I think even if it's a 3 minute task, this scrolling list concept would be good.

> * Right now behavior on switching tasks is to pause the current one and select a new one with it paused, should it immediately start?

Yes, this would be in keeping with studying a user's "flow" with minimal interruption.

> * I don't know if the task title is enough information or if there needs to be a lengthy persistent description to refer to.

The task title should be fine as the persistent mark, maybe with a collapsible panel with details or something like that. This is something to ask Tulane about.
